### ISSUE TITLE
Add Game Gifts (GG) to Modes

### ISSUE THREAD

**Issue by nolddor** [Ryzhehvost/Selective-Loot-and-Transfer-Plugin#3]
Is there any change you can add an specific mode for tradable game gifts so we can loot and transfer everything tradable under Steam->Gift tab?

Thanks

**Comment by Ryzhehvost** [comment]
As you said yourself - gifts are on another inventory tab, and not part of community inventory that handled by this plugin. But good news is - there is already an option to send items from other inventory tabs in asf, even without need of third party plugins. Read about `loot^` and `transfer^` commands in asf wiki for details.

**Comment by nolddor** [comment]
Thanks, it solves the problem.
